website/views.py
from random import random, choice

from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user
from . import db
from flask_login import login_user, login_required, logout_user, current_user
from .models import User, Team, Problem
from time import time
from .auth import encrypt_id
from time import time

views = Blueprint("views", __name__)


@views.route('/', methods=["GET", "POST"])
@login_required
def home():
    team = get_team()
    if not team:
        team = Team(name="", problemsNum=0, index=0, members=[], listNum=0, id=9999)
        return render_template("home.html", user=current_user, team=team, problemset=[], solved=[],
                               code=encrypt_id(team.id), team_mates=[], colors=[])

    sol = get_today_solved_problems_ids(current_user)
    problems = get_today_problems_list()
    team_mates = get_team_mates()
    team_mates_ind = range(len(team_mates))
    team_mates = [(team_mates[i].name, len(get_today_solved_problems_list(team_mates[i])), i) for i in team_mates_ind]
    team_mates = sorted(team_mates, key=lambda x: x[1], reverse=True)

    colors = ['#e6194b', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#911eb4', '#46f0f0', '#f032e6', '#bcf60c']

    while len(colors) < len(team_mates):
        colors += colors

    return render_template("home.html", user=current_user, team=team, problems=problems, solved=sol,
                           code=encrypt_id(team.id), team_mates=team_mates, colors=colors)


@views.route('/solved')
@login_required
def solved():
    problemIndex = int(request.args.get('num'))
    current_user.solutions.append(Problem.query.get(problemIndex))
    db.session.commit()
    return redirect(url_for('views.home'))


@views.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    if not current_user.teamId:
        return redirect(url_for('views.home'))
    if request.method == 'POST':
        if request.form['btn'] == 'change':
            name = request.form.get('name')
            try:
                number = int(request.form.get('number'))
            except:
                flash("Please enter the goal.", category='error')
                return render_template("team.html", user=current_user)

            if not name:
                flash('Please enter a name.', category='error')

            elif number <= 0:
                flash('Problems number per day must be larger than 0.', category='error')

            elif number > 50:
                flash('Woo! take it easy champ, leave some for next month. (max is 50 per day)', category='error')

            else:
                team = get_team()
                team.name = name
                team.problemsNum = number
                db.session.commit()
                flash('Team settings has been modified!', category='success')
                return redirect(url_for('views.settings'))

        elif request.form['btn'] == 'leave':
            current_user.teamId = None
            db.session.commit()
            flash('You left the team!', category='success')
            return redirect(url_for('views.home'))
    return render_template("settings.html", user=current_user, team=get_team())


def get_team():
    return Team.query.get(current_user.teamId)


def get_problem_name(id):
    return Problem.query.get(id).name


def get_problems_start_id():
    return get_team().index + 1


def get_problems_number():
    return get_team().problemsNum


def get_today_problems_list():
    start = get_problems_start_id()
    end = start + get_problems_number()
    return list(Problem.query.filter(Problem.id >= start, Problem.id < end).all())


def get_today_problems_ids():
    start = get_problems_start_id()
    end = start + get_problems_number()
    return [i for i in range(start, end)]


def get_today_problems_names():
    return [get_problem_name(i) for i in get_today_problems_ids()]


def get_today_solved_problems_list(user):
    start = get_problems_start_id()
    end = start + get_problems_number()
    return user.solutions.filter(Problem.id >= start, Problem.id < end).all()


def get_today_solved_problems_ids(user):
    return [i.id for i in get_today_solved_problems_list(user)]


def get_team_mates():
    teamMates = list(User.query.filter_by(teamId=current_user.teamId))
    teamMates.remove(current_user)
    return teamMates

website/templates/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
  integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
  crossorigin="anonymous"
/>
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
  crossorigin="anonymous"
/>
    <title>{% block title %}Home{% endblock %}</title>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class = "collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" id="logout" href="/logout">logout</a>
                <a class="nav-item nav-link" id="home" href="/">Home</a>
                {% else %}
                <a class="nav-item nav-link" id="login" href="/login">Login</a>
                <a class="nav-item nav-link" id="signUp" href="/signup">Sign Up</a>
                {% endif %}
            </div>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
        {% if category == 'error' %}
        <div class="alert alert-danger alert-dismissable fade show", role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% else %}
        <div class="alert alert-success alert-dismissable fade show", role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}
        {% endfor %}
    {% endif %}
    {% endwith %}


    <div class="container">
        {% block content %} {% endblock %}
    </div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
</body>
</html>

website/templates/home.html
{% extends "index.html" %} {% block title %}Home{% endblock %}
{% block content %}
{% if not user.teamId %}
<div class="col text-center" style="margin: 1px;"><a class="btn btn-primary btn-sm d-none d-sm-inline-block" role="button" href="/create-team" style="padding-right: 2;padding-bottom: 2;padding-left: 2;padding-top: 2;height: 30.8px;width: 121.325px;"><i class="fas fa-plus fa-sm text-white-50"></i>&nbsp;Create Team</a><a class="btn btn-primary btn-sm d-none d-sm-inline-block" role="button" href="/join-team" style="margin: 13px;"><i class="fas fa-road fa-sm text-white-50"></i>&nbsp; Join Existing Team</a></div>
{% else %}
<div class="container-fluid">
   <div class="d-sm-flex justify-content-between align-items-center mb-4">
      <h3 class="text-dark mb-0">Hello, {{ user.name.split()[0] }} </h3>
   </div>
   <div class="card-group"></div>
   <div class="row">
      <div class="col order-first">
         <div class="card">
            <div class="row align-items-center no-gutters" style="padding-top: 4px;">
               <div class="col d-md-flex justify-content-md-center"><label class="col-form-label text-danger" style="font-size: 22px;margin-left: 11px;"><strong>{{team.name}}</strong><br></label></div>
               <div class="col d-md-flex justify-content-md-center"><label class="form-label text-primary" style="font-size: 18px;margin-top: 6px; width: 150px;"><strong>Invitation code&nbsp;</strong></label><input readonly value="{{code}}"  class="d-md-flex align-items-md-center" type="text" style="text-align: center;  height: 26.6px;width: 119.4px;margin-top: 5px;margin-left: 6px;margin-bottom: 8px;margin-right: 6px;"></div>
            </div>
         </div>
         <br>
         <div class="card">
            <div class="card-body" style="padding-top: 16px;">
               <div class="row align-items-center no-gutters">
                  <div class="col me-2">
                     <div class="text-uppercase text-info fw-bold text-xs mb-1"><span>progress</span></div>
                     <div class="row g-0 align-items-center">
                        <div class="col-auto">
                           <div class="text-dark fw-bold h5 mb-0 me-3"><span>{{ solved|length }} / {{ team.problemsNum }} </span></div>
                        </div>
                        <div class="col">
                           <div class="progress progress-sm">
                              {% set my_progress = solved|length / team.problemsNum * 100 %}
                              <div class="progress-bar bg-info" aria-valuenow="{{ my_progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ my_progress }}%;"><span class="visually-hidden">{{ my_progress }}%</span></div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <br>
         <div class="card" style="text-align: left;">
            <div class="card-header d-flex justify-content-between align-items-center">
               <h6 class="text-primary fw-bold m-0">Today's Problemset</h6>
               <div class="dropdown no-arrow">
                  <button class="btn btn-link btn-sm dropdown-toggle" aria-expanded="false" data-bs-toggle="dropdown" type="button"><i class="fas fa-ellipsis-v text-gray-400"></i></button>
                  <div class="dropdown-menu shadow dropdown-menu-end animated--fade-in">
                  </div>
               </div>
            </div>
            <div class="card-body">
               <ul class="list-group">
                  {% for problem in problems %}
                  <li class="list-group-item" {% if problem.id in solved %} style="background-color: springgreen;" {% else %} style="background-color: mintcream;" {% endif %} >
                  <div class="row align-items-center no-gutters">
                     <div class="col me-2"><span style="font-size: 20px;font-weight: bold;font-family: Nunito, sans-serif;">{{ problem.name }}</span></div>
                     {% set url = 'https://codeforces.com/problemset/problem/' + problem.name %}
                     <div class="col-auto">
                        {% if problem.id not in solved %}
                        <button class="btn btn-primary" type="button" style="text-align: center;padding-right: 11px;margin-right: 18px;height: 35px;width: 86.125px;" onclick="window.location.href='{{ url_for( 'views.solved', num=problem.id) }}';">Solved?</button>
                        {% endif %}
                        <button  class="btn btn-primary" type="button" target='_blank'  style="text-align: center;padding-right: 11px;margin-left: 0px;height: 35px;width: 105.125px;margin-right: 0px;background: rgb(162,62,239);color: var(--bs-body-bg);border-style: none;border-color: var(--bs-blue);" onclick= "window.open('{{url}}','_blank');return false;">Codeforces</button>
                     </div>
                  </div>
                  </li>
                  {% endfor %}
               </ul>
            </div>
         </div>
         <br>
      </div>
      <div class="col">
         <div class="card">
            <div class="card-header py-3">
               <h6 class="text-primary fw-bold m-0">Team mates progress</h6>
            </div>
            <div class="card-body">
               {% for name, num, i in team_mates %}
               {% set m = team_mates[i] %}
               <h4 class="small fw-bold" style="color: red">{{ name }}<span class="float-end" style="color: black">{{ num }} / {{ team.problemsNum }}</span></h4>
               <div class="progress progress mb-4">
                  <div class="progress-bar bg-gradient-primary"  aria-valuenow="{{num / team.problemsNum * 100 }}" aria-valuemin="0" aria-valuemax="100" style=" background: {{ colors[i] }}; width: {{ num / team.problemsNum * 100 }}%;"><span class="visually-hidden">{{ num / team.problemsNum }}%</span></div>
               </div>
               {% endfor %}
            </div>
         </div>
      </div>
   </div>
</div>
{% endif %}
{% endblock %}

website/templates/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title> TEAMSOLVE </title>
    <link rel="stylesheet" href="static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="static/fonts/fontawesome-all.min.css">
    <link rel="stylesheet" href="static/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="static/fonts/fontawesome5-overrides.min.css">
    <link rel="stylesheet" href="static/css/untitled.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>

</head>

<body id="page-top" >
    <div id="wrapper">
        <div class="visible"></div>
        <div class="d-flex flex-column" id="content-wrapper"  style="background: ghostwhite">
            <div id="content">
                <nav class="navbar navbar-light navbar-expand-md bg-white" style="margin-bottom: 24px;margin-top: 9px;font-size: 17px;">
                    <div class="container-fluid"><a  class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="#"><i class="fas fa-code" style="font-size: 25px; "></i>
                            <div class="sidebar-brand-icon rotate-n-15"></div>
                            <div class="sidebar-brand-text mx-3" style="font-size: 25px;"><span>TEAMSOLVE</span></div>
                        </a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-2"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse d-md-flex d-lg-flex" style="     justify-content: right!important;" id="navcol-2">
                            <ul class="navbar-nav d-md-flex">
                                {% if user.id %}
                                <li class="nav-item"><a class="nav-link active d-md-flex align-items-md-start" href="/" style="margin-right: 17px;"><i class="fas fa-tachometer-alt" style="margin-top: 3px;"></i><span>&nbsp;Dashboard</span></a></li>
                                    {% if user.teamId %}
                                        <li class="nav-item"><a class="nav-link active d-md-flex align-items-md-start" href="/settings" style="margin-right: 17px;"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icon-tabler-settings d-lg-flex" style="margin-top: 3px;font-size: 18px;">
                                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                            <path d="M10.325 4.317c.426 -1.756 2.924 -1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543 -.94 3.31 .826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756 .426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543 -.826 3.31 -2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756 -2.924 1.756 -3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543 .94 -3.31 -.826 -2.37 -2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756 -.426 -1.756 -2.924 0 -3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94 -1.543 .826 -3.31 2.37 -2.37c1 .608 2.296 .07 2.572 -1.065z"></path>
                                            <circle cx="12" cy="12" r="3"></circle>
                                        </svg><span class="d-lg-flex align-items-lg-start">&nbsp;Team Settings</span></a></li>
                                    {% endif %}
                            </ul>
                                <ul class="navbar-nav d-md-flex justify-content-md-center">
                                    <li class="nav-item"><a class="nav-link active d-md-flex align-items-md-start" id="logout" href="/logout"><i class="fas fa-user" style="margin-top: 2px;"></i><span>&nbsp;Logout</span></a></li>
                                </ul>
                                {% else %}
                                <div class="container" >
                                        {% block buttons %} {% endblock %}
                                </div>
                                {% endif %}
                        </div>
                    </div>
                </nav>
                <div class="collapse navbar-collapse"></div>
                    {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                        {% if category == 'error' %}
                        <div role="alert" class="alert alert-danger alert-dismissible"><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button><span><strong>Alert! </strong>
                            {{ message }}
                        </span></div></div>
                        {% else %}
                        <div role="alert" class="alert alert-success alert-dismissible"><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button><span><strong>Success! </strong>
                            {{ message }}</span></div>
                        </div>
                        {% endif %}
                        {% endfor %}
                    {% endif %}
                    {% endwith %}
                        <div class="container" >
                            {% block content %} {% endblock %}
                        </div>
                </div>
        </div><a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>
    <script src="static/bootstrap/js/bootstrap.min.js"></script>
    <script src="static/js/chart.min.js"></script>
    <script src="static/js/bs-init.js"></script>
    <script src="static/js/theme.js"></script>
</body>

</html>

website/templates/join-team.html
{% extends "index.html" %} {% block title %}Home{% endblock %}
{% block content %}
<div style="padding: 49px;"><form method="POST">
    <br>
  <h3 style="color: black;" align="center">Join Team</h3>
  <br>
  <div class="form-group">
    <center>
    <input type="code" class="form-control" id="code" name="code" style="width: 400px;" placeholder="Enter invitation Code">
    </center>
  </div>
  <br>
        <div class="d-md-flex justify-content-md-center mb-3"><button class="btn btn-primary d-md-flex justify-content-md-center" type="submit">join</button></div>


</form></div>
 <br> <br> <br> <br> <br> <br> <br> <br>
{% endblock %}

website/templates/login.html
{% extends "index.html" %} {% block title %}Home{% endblock %}
{% block buttons %}
   <li class="nav-item"><a class="nav-link active d-md-flex align-items-md-start" id="login" href="/signup"><i class="fas fa-user" style="margin-top: 2px;"></i><span>&nbsp; Register</span></a></li>
{% endblock %}
{% block content %}
<div style="padding: 49px;">
   <form method="POST">
      <h3 style="color: black; "  align="center">Sign in</h3>
      <br>
      <br>
      <center>
         <div class="form-group">
            <label style="color: black;"  form="name">Email Address</label>
            <input type="email" type='email' style="color: #2f3037; width: 400px;" class="form-control" id="email" name="email" placeholder="Enter email">
         </div>
         <br>
         <div class="form-group">
            <label style="color: black;"  form="name">Password</label>
            <input type="password" type='password' style="color: #2f3037; width: 400px;" class="form-control" id="password" name="password" placeholder="Enter password">
         </div>
         <br>
         <br>
         <button type="submit" class="btn btn-primary">Sign in</button>
      </center>
   </form>
</div>
<br> <br> <br> <br>
{% endblock %}

website/templates/settings.html
{% extends "index.html" %} {% block title %}Home{% endblock %}
{% block content %}
<div style="padding: 49px;">
   <form method="POST">
      <h3 style="color: black; "  align="center">Change team settings</h3>
      <br>
      <br>
      <center>
      <div class="form-group">
         <label style="color: black;"  form="name">Team Name</label>
         <input type="name" style="width: 400px; color: red" class="form-control" id="name" value="{{team.name}}" name="name" placeholder="Enter Name ">
      </div>
      <br>
      <div class="form-group">
         <label style="width: 100px;color: black;" form="name">Daily goal</label>
         <input type="number" style="width: 300px;color: red; text-align: center;" step="1" min="1" max="50" value="{{team.problemsNum}}" class="form-control" id="number" name="number" placeholder="Enter problems number per day">
      </div>
      <br>
      <br>
      <button type="submit" name="btn" value="change" class="btn btn-primary">Submit</button>
      </center>
   </form>
   <br>
   <br>
   <br>
   <hr style="width: auto"/>
   <br>
   <br>
   <br>
   <form  method="POST">

      <center>
         <button type="submit" name="btn" value="leave" class="btn btn-danger">Leave Team</button>
      </center>
   </form>
</div>
<br> <br>
{% endblock %}

website/templates/signup.html
{% extends "index.html" %} {% block title %}Home{% endblock %}
{% block buttons %}
<li class="nav-item"><a class="nav-link active d-md-flex align-items-md-start" id="login" href="/login"><i class="fas fa-user" style="margin-top: 2px;"></i><span>&nbsp; Sign in</span></a></li>
{% endblock %}
{% block content %}
<div style="padding: 49px;">
   <form method="POST">
      <h3 style="color: black; "  align="center">Create Account</h3>
      <br>
      <center>
         <div class="form-group">
            <label style="color: black;"  form="name">Email Address</label>
            <input type="email" type='email' value="{{email}}" style=" color: #2f3037; width: 400px;" class="form-control" id="email" name="email" placeholder="Enter email">
         </div>
         <br>
         <div class="form-group">
            <label style="color: black;"  form="name">Name</label>
            <input type="name" type='text' value="{{name}}" style=" color: #2f3037; width: 400px;" class="form-control" id="name" name="name" placeholder="Enter your name">
         </div>
         <br>
         <div class="form-group">
            <label style="color: black;"  form="name">Password</label>
            <input type="password" type='password1' style="color: #2f3037; width: 400px;" class="form-control" id="password1" name="password1" placeholder="Enter password">
         </div>
         <br>
         <div class="form-group">
            <label style="color: black;"  form="name">Password (Confirm)</label>
            <input type="password" type='password' style="color: #2f3037; width: 400px;" class="form-control" id="password2" name="password2" placeholder="Confirm password">
         </div>
         <br>
         <br>
         <button type="submit" class="btn btn-primary">Register</button>
      </center>
   </form>
</div>
<br> <br>
{% endblock %}

website/templates/team.html
{% extends "index.html" %} {% block title %}Home{% endblock %}
{% block content %}
<div style="padding: 49px;"><form method="POST">
  <h3 style="color: black; "  align="center">Create Team</h3>
  <br>
  <br>
  <center>
  <div class="form-group">
    <label style="color: black;"  form="name">Team Name</label>
    <input type="name" style="width: 400px;" class="form-control" id="name" name="name" placeholder="Enter Name ">
  </div>
  <br>
  <div class="form-group">
    <label style="width: 100px;color: black;" form="name">Daily goal</label>
    <input type="number" style="width: 300px;color: red; text-align: center;" step="1" min="1" max="50" class="form-control" id="number" name="number" placeholder="Enter problems number per day">
  </div>

  <br>
  <br>
  <button type="create" class="btn btn-primary">Create</button>
</form></div>
</center>
 <br> <br> <br> <br>
{% endblock %}